# Generated by Django 4.1.4 on 2022-12-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('categ_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='producto.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nobre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
                ('slug', models.CharField(max_length=50, verbose_name='Slug')),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio oferta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='producto.categoria')),
                ('marca_codigo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='producto.marca')),
            ],
        ),
        migrations.CreateModel(
            name='PResentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Stock Actual')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Precio')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.color')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.medida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
