# Generated by Django 4.1.4 on 2022-12-30 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ImageField(upload_to='productos', verbose_name='Nombre')),
                ('order', models.SmallIntegerField(verbose_name='Orden')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='producto.producto')),
            ],
        ),
    ]
