# Generated by Django 4.1.4 on 2022-12-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_rename_nobre_marca_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_oferta',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Porcentaje descuento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Precio oferta'),
        ),
    ]
