# Generated by Django 4.1.4 on 2022-12-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_categoria_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Porcentaje descuento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Precio oferta'),
        ),
    ]
