# Generated by Django 4.1.4 on 2023-01-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_producto_porcentaje_oferta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='presentacion',
            options={'verbose_name': 'Presentación', 'verbose_name_plural': 'Presentaciones'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
