# Generated by Django 4.1.5 on 2023-01-14 21:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_categoria_options_alter_imagen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='nombre', unique_with=['nombre']),
        ),
    ]
